name: Test building the project in different environments

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: 
          - {image: 'debian:bullseye', dockerfile: 'Dockerfile_DEBIAN'}
          - {image: 'debian:bookworm', dockerfile: 'Dockerfile_DEBIAN'}
          - {image: 'ubuntu:20.04', dockerfile: 'Dockerfile_DEBIAN'}
          - {image: 'ubuntu:22.04', dockerfile: 'Dockerfile_DEBIAN'}
          - {image: 'rockylinux:8', dockerfile: 'Dockerfile_RHEL'}
          - {image: 'rockylinux:9', dockerfile: 'Dockerfile_RHEL'}
          - {image: 'oraclelinux:8', dockerfile: 'Dockerfile_RHEL'}
          - {image: 'oraclelinux:9', dockerfile: 'Dockerfile_RHEL'}
      fail-fast: false

    runs-on: ubuntu-latest # This is only the host

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build \
            --build-arg BASE_OS=${{ matrix.os.image }} \
            -f docker/${{ matrix.os.dockerfile }} \
            -t test_${{ matrix.os.image }} .

      - name: Test building project
        run: |
          docker run --rm -t -v "$(pwd)":/workdir -t test_${{ matrix.os.image }} \
          /bin/bash -ec "mkdir build/ && cd build/ && cmake .. && make -j"

      - name: Print linked libs
        run: |
          ldd bin/main
